### ISSUE TITLE
请问The empty path didn’t match any of these.怎么解决QWQ

### ISSUE THREAD

**Issue by Se7en-exe** [xishandong/Django_Server_redbook#2]
![QQ截图20240612111049](https://github.com/xishandong/Django_Server_redbook/assets/115208577/aeb3b1c8-97e8-4d12-82be-62b932c4efd0)
urls.py的代码我都没改过，端口我设置成了5173，我问ChatGPT和百度，好半天都没有解决QWQ,我是django新手

**Comment by xishandong** [comment]
django只是一个后端接口，前端页面是vue，这个是前后端分离项目
